// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjtxesxfptsmqhcalkcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdHhlc3hmcHRzbXFoY2Fsa2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTU2NDQsImV4cCI6MjA3MDU3MTY0NH0.UeKQduag5Oxvl5s8QWYNGvmp3hp1N9EChyIggrh-gD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});